Repository gardener/virtual-garden, pull requests merged in 2022-02, with the labels that each got.

#15 Harmoninze blueprint
  .gitignore
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/virtual-garden-deploy-execution.yaml
  .landscaper/blueprint/virtual-garden-export-execution.yaml
  cmd/virtual-garden/app/virtual_garden.go
  docs/deploy-virtual-garden-with-landscaper.md
  example/imports.yaml
  hack/create-installation.sh
  hack/generate-cd.sh
  pkg/api/exports.go
  pkg/api/imports.go
  pkg/api/loader/exports_test.go
  pkg/api/loader/imports_test.go
  pkg/api/validation/imports.go
  pkg/api/validation/imports_test.go
  pkg/virtualgarden/etcd_service.go
  pkg/virtualgarden/kube_api_server_certificates.go
  pkg/virtualgarden/kube_api_server_certificates_test.go
  pkg/virtualgarden/kube_api_server_configmaps_test.go
  pkg/virtualgarden/kube_api_server_deployment_controller_manager_test.go
  pkg/virtualgarden/kube_api_server_deployments_test.go
  pkg/virtualgarden/kube_api_server_misc_test.go
  pkg/virtualgarden/kube_api_server_podautoscaling_test.go
  pkg/virtualgarden/kube_api_server_secrets_test.go
  pkg/virtualgarden/operation.go
  pkg/virtualgarden/operation_test.go
  test/e2e/e2e_test.go
Labels: kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/m

#16 Update image versions
  .landscaper/resources.yaml
Labels: area/quality, kind/bug, reviewed/lgtm, needs/ok-to-test, size/xs

#19 external references relation corrected
  .landscaper/resources.yaml
Labels: area/delivery, kind/bug, reviewed/lgtm, needs/ok-to-test, size/xs
